---
- src: git@github.com:lekctut/clickhouse.git
  scm: git
  version: "1.0"
  name: clickhouse 

- src: git@github.com:lekctut/vector.git
  scm: git
  version: "1.0"
  name: vector 

- src: git@github.com:lekctut/lighthouse.git
  scm: git
  version: "1.0"
  name: lighthouse 